remote_theme: just-the-docs/just-the-docs
title: Marc Galbraith
tagline: Marc Galbraith | My blog and work history
url: https://marcgalbraith.com
email: marc@marcgalbraith.com
description: My blog and work history
color_scheme: dark
base_url: '/'
excerpt_separator: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag
feed:
  path: /blog/feed.atom
  
# Define Jekyll collections
collections:
  # Define a collection named "resume", its documents reside in the "_resume" directory
  resume:
    permalink: "/:collection/:path/"
    output: true
  # Define a collection named "resume", its documents reside in the "_resume" directory 
  blogs:
    permalink: "/:collection/:path/"
    output: true 
 

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    blogs:
      name: By Interest
    # Reference the "resume" collection
    resume:
      # Give the collection a name
      name: CV
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
